// Lilaas AS — client-specific content

const BASE = "https://lilaas.no/wp-content";

export const images = {
  logo:       `${BASE}/uploads/2024/03/607e9ed60d6f223e30434233_Group-1-1.svg`,
  hero:       `${BASE}/smush-webp/2024/03/Hovedbilde-main-page.png.webp`,
  factory:    `${BASE}/smush-webp/2024/11/smart-lilaas-02-1024x683-1.jpg.webp`,
  press:      `${BASE}/smush-webp/2024/02/60a64fea845d6cd465c15c9f_Finansavisen-Lilaas-2020-scaled-p-1600-1200x851.jpeg.webp`,
  maritime:   `${BASE}/smush-webp/2024/02/60bf1cf069312115a43ccb41_maritime-1200x550.jpg.webp`,
  boatAtSea:  `${BASE}/smush-webp/2024/02/60ba0c4258b72035e623010c_boat-at-sea-1200x450.jpg.webp`,
  hospitals:  `${BASE}/smush-webp/2024/02/60bf1aa8026fb268a8fbf05e_hospitals-1200x550.jpg.webp`,
  precision:  `${BASE}/smush-webp/2024/02/60af49ca343b5f7834148f76_precision-mechanics-1.png.webp`,
  l01:   `${BASE}/smush-webp/2024/02/60ba334c2c1c2b29d84526e4_front-L01.png.webp`,
  lf120: `${BASE}/smush-webp/2024/02/611a6fc1f228b0ea55bd20cd_lf120-single1.png.webp`,
  lf180: `${BASE}/smush-webp/2024/02/611a729aeb0ce659557fa771_lf180.png.webp`,
  le90:  `${BASE}/smush-webp/2024/02/6087e956355813def0674b83_le90-section1-1.png.webp`,
  layer1:`${BASE}/smush-webp/2024/02/611a5f6eb2a5cd298bc6f876_Layer-1.png.webp`,
  lf70:  `${BASE}/smush-webp/2024/02/Untitled-14.png.webp`,
};

export const brand = {
  name: "Lilaas",
  domain: "lilaas.no",
  founded: 1961,
  employees: 60,
  location: "Kongeveien 75, 3188 Horten, Norway",
  phone: "+47 416 33 000",
  email: "lilaas@lilaas.no",
  phoneHours: "08:00–16:00",
  ceo: "Espen Hoff",
  ceoQuote: "We design, engineer, and produce everything in-house — mechanics, software, assembly. We're known for solving technically difficult problems.",
  description: "Lilaas is one of the world's leading manufacturers of control levers and joysticks for maritime vessels.",
  revenueShare: { maritime: 75, precision: 25 },
  exportShare: 50,
};

export const navLinks = [
  { id: "about",      label: "About" },
  { id: "products",   label: "Products" },
  { id: "industries", label: "Industries" },
  { id: "clients",    label: "Clients" },
  { id: "contact",    label: "Contact" },
];

export const stats = [
  { value: "60+", label: "Years of experience" },
  { value: "60",  label: "Employees" },
  { value: "50",  label: "Exported globally" },
  { value: "4",   label: "Industries" },
];

export const products = [
  {
    id: "l01",
    title: "L01 — Flagship",
    subtitle: "Synchronised bridge console",
    description: "L01 is Lilaas' flagship product. Fully integrated electronics with synchronised bridge console technology. Used on all types of vessels worldwide.",
    longDescription: [
      "The L01 is the result of over six decades of maritime engineering expertise. Engineered from the ground up for the modern bridge, it features fully synchronised console technology that allows seamless master/slave operation from multiple bridge stations simultaneously. Every component — from the precision-machined aluminium housing to the custom-developed electronics — is designed and produced in-house at Lilaas' facility in Horten, Norway.",
      "Its robust IP66-sealed enclosure ensures complete protection against water jets and heavy seas, while the DNV-certified design meets the most stringent classification society requirements. The integrated CAN bus interface enables plug-and-play connectivity with all major vessel automation systems, and the lever's haptic feedback mechanism gives operators confident, fatigue-free control even in the roughest conditions.",
    ],
    technicalSpecs: {
      "Protection rating": "IP66",
      "Certification": "DNV",
      "Interface": "CAN bus",
      "Configuration": "Master / Slave",
      "Housing material": "Anodised aluminium",
      "Operating temperature": "−25 °C to +70 °C",
      "Supply voltage": "12–24 V DC",
      "Output signal": "Analogue + CAN J1939",
      "Mounting": "Panel / console mount",
      "Weight": "Approx. 1.4 kg",
    },
    certifications: ["DNV", "IP66", "CE"],
    applications: [
      "Offshore supply vessels",
      "Ferries & ro-ro",
      "Tankers",
      "Cruise ships",
      "Fishing vessels",
      "Research vessels",
    ],
    specs: ["IP66", "DNV certified", "CAN bus", "Master/Slave"],
    image: images.l01,
    link: "https://lilaas.no/product/l01/",
  },
  {
    id: "lf120",
    title: "LF120 — Propulsion",
    subtitle: "120° movement · IP66",
    description: "Single-axis control lever for propulsion control. Robust aluminium construction, DNV and CRS certified.",
    longDescription: [
      "The LF120 is Lilaas' core single-axis propulsion control lever, designed for demanding maritime environments where reliability is non-negotiable. With a 120° arc of travel it covers the full range from full ahead to full astern with precise, well-defined detents at the neutral and clutch-engage positions. The lever body is CNC-machined from solid aluminium alloy and hard-anodised for maximum corrosion resistance.",
      "Certified by both DNV and CRS, the LF120 meets the classification requirements of the world's major flag states. Its modular internal design allows the lever to be configured with optional integrated switches, buzzer outputs, and emergency-stop contacts without any external wiring harness modifications — simplifying installation and reducing shipyard labour costs significantly.",
    ],
    technicalSpecs: {
      "Protection rating": "IP66",
      "Certification": "DNV / CRS",
      "Range of motion": "120°",
      "Housing material": "Anodised aluminium",
      "Detents": "Neutral, clutch-engage",
      "Operating temperature": "−25 °C to +70 °C",
      "Supply voltage": "12–24 V DC",
      "Output signal": "Analogue (0–10 V / 4–20 mA)",
      "Optional switches": "Up to 4 integrated",
      "Weight": "Approx. 0.9 kg",
    },
    certifications: ["DNV", "CRS", "IP66", "CE"],
    applications: [
      "Fishing vessels",
      "Patrol boats",
      "Work boats",
      "Inland waterway vessels",
      "Small ferries",
      "Tugboats",
    ],
    specs: ["IP66", "120° range", "DNV/CRS", "Aluminium body"],
    image: images.lf120,
    link: "https://lilaas.no/product/lf120/",
  },
  {
    id: "lf180",
    title: "LF180 — Heavy Duty",
    subtitle: "180° movement · Rugged",
    description: "Large, rugged control lever for demanding maritime use. 180° range of motion. Available with motorised axes.",
    longDescription: [
      "The LF180 is built for the most demanding propulsion control applications in the commercial maritime sector. Its extended 180° travel arc enables fine-grain speed control across the entire engine range, and the heavy-duty lever head — machined from solid stainless steel — withstands the sustained physical loads of continuous wheelhouse operation. The optional motorised axis module allows the lever to be driven remotely to a set-point, enabling dynamic positioning and autopilot follow-up modes.",
      "Integrated switch banks can be factory-configured with up to eight positions for clutch, horn, alarm-acknowledge, and navigation-light functions, all within the sealed IP66 housing. The LF180 is offered in single, twin, and triple axis configurations and can be ganged into a full bridge console unit in conjunction with the L01 system — giving shipyards and system integrators maximum flexibility during newbuild and retrofit projects.",
    ],
    technicalSpecs: {
      "Protection rating": "IP66",
      "Range of motion": "180°",
      "Motorised option": "Yes — optional servo motor",
      "Integrated switches": "Up to 8 positions",
      "Housing material": "Stainless steel / anodised aluminium",
      "Operating temperature": "−30 °C to +70 °C",
      "Supply voltage": "24 V DC",
      "Output signal": "Analogue + optional CAN",
      "Configurations": "Single / twin / triple axis",
      "Weight": "Approx. 2.1 kg",
    },
    certifications: ["IP66", "CE", "DNV (on request)"],
    applications: [
      "Large offshore vessels",
      "PSVs & AHTSs",
      "Dredgers",
      "Cable-layers",
      "Heavy-lift vessels",
      "Platform supply",
    ],
    specs: ["IP66", "180° range", "Motorised option", "Built-in switches"],
    image: images.lf180,
    link: "https://lilaas.no/product/lf180/",
  },
  {
    id: "le90",
    title: "LE90 — Rudder",
    subtitle: "Rudder & thruster control",
    description: "Precise control of vessel direction. High operational reliability and long service life for rudder and thruster.",
    longDescription: [
      "The LE90 is engineered specifically for rudder and bow/stern thruster control, providing the precise, linear response that navigators rely on for close-quarters manoeuvring in harbours and restricted waterways. The 90° travel arc maps directly to the rudder's hard-over-to-hard-over deflection range, with a spring-return-to-centre option available for single-handed operation. Magnetic contactless sensors eliminate wear on moving parts and ensure accurate position feedback throughout the product's service life.",
      "The LE90 is fully compatible with Lilaas' AESS network, allowing it to function as a slave station to any master lever on the same CAN bus segment. Its compact footprint and standard panel-cut dimensions make it the preferred choice for retrofit installations on existing vessels where console space is limited, and its sealed IP66 housing guarantees reliable operation in the most hostile wheelhouse environments.",
    ],
    technicalSpecs: {
      "Protection rating": "IP66",
      "Range of motion": "90°",
      "Application": "Rudder & thruster",
      "Return to centre": "Optional spring",
      "Position sensor": "Contactless magnetic",
      "Operating temperature": "−25 °C to +70 °C",
      "Supply voltage": "12–24 V DC",
      "Output signal": "Analogue (±5 V / 4–20 mA)",
      "AESS compatible": "Yes",
      "Weight": "Approx. 0.7 kg",
    },
    certifications: ["IP66", "CE"],
    applications: [
      "All vessel types (rudder)",
      "Bow thruster control",
      "Stern thruster control",
      "Dynamic positioning consoles",
      "Ferry bridge consoles",
      "Harbour tugs",
    ],
    specs: ["IP66", "90° range", "Rudder control", "Thruster"],
    image: images.le90,
    link: "https://lilaas.no/product/le90/",
  },
  {
    id: "joystick",
    title: "Joystick / Azimuth",
    subtitle: "Multi-axis · AESS · CAN",
    description: "Advanced multi-axis joystick with AESS. Master/slave over CAN network — simultaneous operation from any bridge position.",
    longDescription: [
      "Lilaas' multi-axis joystick and azimuth controller is the command interface of choice for vessels equipped with azimuth thrusters, Voith-Schneider propellers, and combined thruster-rudder systems. The hall-effect magnetic sensing array provides absolute position feedback on all axes with zero hysteresis and no contact wear — critical for the precise positioning demands of offshore operations, cable-laying, and dynamic positioning class 2 and 3 installations.",
      "Built on Lilaas' proprietary AESS (Azimuth Electronic Shaft System) platform, the joystick integrates seamlessly into any CAN bus network. Each unit can be configured as master or slave at boot time, enabling a vessel to have fully functional duplicate controls at the main bridge, the bridge wings, and an aft-station — all linked without additional I/O hardware. The ruggedised housing withstands the vibration and shock loads of high-speed patrol craft and offshore supply vessels alike.",
    ],
    technicalSpecs: {
      "Axes": "2–3 (configurable)",
      "Technology": "Lilaas AESS",
      "Interface": "CAN bus (J1939)",
      "Configuration": "Master / Slave",
      "Position sensing": "Contactless magnetic (Hall effect)",
      "Protection rating": "IP66",
      "Supply voltage": "24 V DC",
      "Operating temperature": "−25 °C to +70 °C",
      "DP class": "DP2 / DP3 compatible",
      "Weight": "Approx. 1.1 kg",
    },
    certifications: ["IP66", "DNV", "CE", "AESS certified"],
    applications: [
      "Dynamic positioning vessels",
      "Azimuth thruster vessels",
      "Cable-lay & pipe-lay ships",
      "Offshore construction",
      "Platform supply vessels",
      "High-speed craft",
    ],
    specs: ["Multi-axis", "AESS", "CAN bus", "Magnetic sensors"],
    image: images.layer1,
    link: "https://lilaas.no/control-levers/",
  },
  {
    id: "lf70",
    title: "LF70 — Dual Axis",
    subtitle: "Dual-axis azimuth",
    description: "Dual-axis azimuth control lever for maritime use. Combines engine speed and propeller direction in one compact design.",
    longDescription: [
      "The LF70 combines two independent axes in a single compact lever head: a fore-aft axis for engine speed and thrust control (120° travel) and a rotational axis for propeller/azimuth direction (360° continuous rotation). This two-in-one design eliminates the need for a separate rudder lever on vessels fitted with steerable propulsion units, dramatically reducing console footprint while improving the ergonomics of single-handed manoeuvring.",
      "DNV and CRS certified for commercial vessel installations, the LF70 is constructed from the same hard-anodised aluminium alloy used across the Lilaas product family. The dual-axis output is available in analogue voltage, current-loop, or CAN bus formats — allowing it to interface directly with all major vessel management and dynamic-positioning systems without external signal converters. A factory-wired emergency-stop circuit is included as standard.",
    ],
    technicalSpecs: {
      "Protection rating": "IP66",
      "Certification": "DNV / CRS",
      "Fore-aft travel": "120°",
      "Rotational travel": "360° continuous",
      "Housing material": "Anodised aluminium",
      "Operating temperature": "−25 °C to +70 °C",
      "Supply voltage": "12–24 V DC",
      "Output signal": "Analogue + CAN (optional)",
      "Emergency stop": "Integrated (standard)",
      "Weight": "Approx. 1.2 kg",
    },
    certifications: ["DNV", "CRS", "IP66", "CE"],
    applications: [
      "Azimuth propulsion vessels",
      "Compact bridge consoles",
      "Fishing vessels",
      "Harbour ferries",
      "Offshore support vessels",
      "Inland waterway craft",
    ],
    specs: ["IP66", "Dual axis", "360° horizontal", "DNV/CRS"],
    image: images.lf70,
    link: "https://lilaas.no/product/lf70/",
  },
];

export const industries = [
  {
    title: "Maritime & Offshore",
    description: "75% of revenue. Control levers and joysticks on everything from fishing boats and ferries to supply vessels, tankers and cruise ships.",
    icon: "⚓",
    color: "#f9840c",
    share: "75%",
    image: images.boatAtSea,
  },
  {
    title: "Defence",
    description: "Military-certified precision components with the strictest requirements for reliability and documentation.",
    icon: "🛡️",
    color: "#e07008",
    share: "",
    image: images.factory,
  },
  {
    title: "Medicine",
    description: "High-precision components for medical equipment with full traceability and quality documentation.",
    icon: "🏥",
    color: "#d06000",
    share: "",
    image: images.hospitals,
  },
  {
    title: "Space & Research",
    description: "Precision components for space and scientific research, including CERN's Large Hadron Collider.",
    icon: "🚀",
    color: "#c05000",
    share: "",
    image: images.precision,
  },
];

export const clients = [
  { name: "Kongsberg Maritime", description: "World-leading supplier of maritime technology solutions.", logo: "🇳🇴" },
  { name: "Wärtsilä",           description: "Global leader in advanced technologies for maritime and energy markets.", logo: "🌐" },
  { name: "CERN",               description: "European Organization for Nuclear Research — Large Hadron Collider.", logo: "⚛️" },
];

export const features = [
  { icon: "🏭", title: "All in-house",          text: "Mechanics, software and assembly — all under one roof in Horten." },
  { icon: "🎯", title: "Technically demanding", text: "Specialised in solving what others can't." },
  { icon: "🌍", title: "Global exports",        text: "~50% of products exported directly to the world." },
  { icon: "🤖", title: "Autonomy-ready",        text: "Positioned for the future of autonomous vessels." },
];
